logger: wandb
max_steps: 6000  # short finetune after pruning
model:
  renderer: internal.renderers.gsplat_renderer.GSPlatRenderer
  light_gaussian:
    prune_steps:
      - 1         # prune immediately after loading
    prune_percent: 0.5
    prune_decay: 1.0
    v_pow: 0.1
    semantic_importance_weight: 1.0
    semantic_importance_vis_weight: 1.0
# keep other defaults from base configs (lr, schedulers, etc.)
data:
  parser:
    class_path: Feature3DGSColmap
    init_args:
      split_mode: experiment
      feature_dir: "rgb_feature_langseg"
      filename_suffix: "_fmap_CxHxW"
      filename_include_image_ext: false