max_steps: 6000  # short finetune after pruning
model:
  renderer: internal.renderers.gsplat_renderer.GSPlatRenderer
  light_gaussian:
    prune_steps:
      - 1         # prune immediately after loading
    prune_percent: 0.5
    prune_decay: 1.0
    v_pow: 0.1
    semantic_importance_weight: 1.0
    semantic_importance_vis_weight: 1.0
# keep other defaults from base configs (lr, schedulers, etc.)
